// <auto-generated />
using System;
using ConSecOrg.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConSecOrg.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260514140000_AddChatMessageEncryption")]
    partial class AddChatMessageEncryption
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ConSecOrg.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uniqueidentifier");
                    b.Property<string>("Action").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                    b.Property<byte[]>("CurrentHash").IsRequired().HasColumnType("VARBINARY(32)");
                    b.Property<string>("DetailsJson").HasColumnType("nvarchar(max)");
                    b.Property<string>("EntityId").HasMaxLength(36).HasColumnType("nvarchar(36)");
                    b.Property<string>("EntityType").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                    b.Property<string>("IpAddress").HasMaxLength(45).HasColumnType("nvarchar(45)");
                    b.Property<byte[]>("PreviousHash").IsRequired().HasColumnType("VARBINARY(32)");
                    b.Property<long>("SequenceNum").ValueGeneratedOnAdd().HasColumnType("bigint");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SequenceNum"));
                    b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
                    b.Property<DateTime>("Timestamp").HasColumnType("datetime2");
                    b.Property<Guid?>("UserId").HasColumnType("uniqueidentifier");
                    b.HasKey("Id");
                    b.HasIndex("SequenceNum").IsUnique();
                    b.HasIndex("Timestamp");
                    b.HasIndex("UserId");
                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("ConSecOrg.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                    b.Property<string>("Color").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<Guid?>("CreatedBy").HasColumnType("uniqueidentifier");
                    b.Property<string>("Icon").HasColumnType("nvarchar(max)");
                    b.Property<string>("Name").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<DateTime>("UpdatedAt").HasColumnType("datetime2");
                    b.Property<Guid?>("UpdatedBy").HasColumnType("uniqueidentifier");
                    b.Property<Guid>("UserId").HasColumnType("uniqueidentifier");
                    b.HasKey("Id");
                    b.ToTable("Categories");
                });

            modelBuilder.Entity("ConSecOrg.Domain.Entities.ChatLastRead", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                    b.Property<string>("ChatKey").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                    b.Property<DateTime>("LastReadAt").HasColumnType("datetime2");
                    b.Property<Guid>("UserId").HasColumnType("uniqueidentifier");
                    b.HasKey("Id");
                    b.HasIndex("UserId", "ChatKey").IsUnique();
                    b.ToTable("ChatLastReads");
                });

            modelBuilder.Entity("ConSecOrg.Domain.Entities.ChatMessage", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                    b.Property<string>("AttachmentFileId").HasColumnType("nvarchar(max)");
                    b.Property<string>("AttachmentFileName").HasColumnType("nvarchar(max)");
                    b.Property<long?>("AttachmentSize").HasColumnType("bigint");
                    b.Property<Guid?>("GroupChatId").HasColumnType("uniqueidentifier");
                    b.Property<Guid?>("ProjectId").HasColumnType("uniqueidentifier");
                    b.Property<Guid>("SenderUserId").HasColumnType("uniqueidentifier");
                    b.Property<DateTime>("SentAt").HasColumnType("datetime2");
                    b.Property<string>("Text").IsRequired().HasMaxLength(4000).HasColumnType("nvarchar(4000)");
                    b.Property<byte[]>("TextCipher").HasColumnName("text_cipher").HasColumnType("VARBINARY(MAX)");
                    b.Property<byte[]>("TextHmac").HasColumnName("text_hmac").HasColumnType("VARBINARY(32)");
                    b.Property<byte[]>("TextNonce").HasColumnName("text_nonce").HasColumnType("VARBINARY(16)");
                    b.Property<Guid?>("ToUserId").HasColumnType("uniqueidentifier");
                    b.HasKey("Id");
                    b.HasIndex("GroupChatId");
                    b.HasIndex("ProjectId", "SentAt");
                    b.HasIndex("SenderUserId", "ToUserId", "SentAt");
                    b.ToTable("chat_messages", (string)null);
                });

            modelBuilder.Entity("ConSecOrg.Domain.Entities.Contact", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uniqueidentifier");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<Guid?>("CreatedBy").HasColumnType("uniqueidentifier");
                    b.Property<Guid?>("LinkedUserId").HasColumnType("uniqueidentifier").HasColumnName("linked_user_id");
                    b.Property<DateTime>("UpdatedAt").HasColumnType("datetime2");
                    b.Property<Guid?>("UpdatedBy").HasColumnType("uniqueidentifier");
                    b.Property<Guid>("UserId").HasColumnType("uniqueidentifier");
                    b.HasKey("Id");
                    b.HasIndex("UserId");
                    b.ToTable("contacts", (string)null);
                });

            modelBuilder.Entity("ConSecOrg.Domain.Entities.ContactRequest", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<Guid?>("CreatedBy").HasColumnType("uniqueidentifier");
                    b.Property<Guid>("ReceiverId").HasColumnType("uniqueidentifier");
                    b.Property<Guid>("SenderId").HasColumnType("uniqueidentifier");
                    b.Property<string>("Status").IsRequired().ValueGeneratedOnAdd().HasMaxLength(20).HasColumnType("nvarchar(20)").HasDefaultValue("Pending");
                    b.Property<DateTime>("UpdatedAt").HasColumnType("datetime2");
                    b.Property<Guid?>("UpdatedBy").HasColumnType("uniqueidentifier");
                    b.HasKey("Id");
                    b.HasIndex("ReceiverId");
                    b.HasIndex("SenderId", "ReceiverId").IsUnique();
                    b.ToTable("contact_requests", (string)null);
                });

            modelBuilder.Entity("ConSecOrg.Domain.Entities.GroupChat", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<Guid>("CreatedByUserId").HasColumnType("uniqueidentifier");
                    b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                    b.HasKey("Id");
                    b.ToTable("group_chats", (string)null);
                });

            modelBuilder.Entity("ConSecOrg.Domain.Entities.GroupChatMember", b =>
                {
                    b.Property<Guid>("GroupChatId").HasColumnType("uniqueidentifier");
                    b.Property<Guid>("UserId").HasColumnType("uniqueidentifier");
                    b.Property<DateTime>("JoinedAt").HasColumnType("datetime2");
                    b.HasKey("GroupChatId", "UserId");
                    b.HasIndex("UserId");
                    b.ToTable("group_chat_members", (string)null);
                });

            modelBuilder.Entity("ConSecOrg.Domain.Entities.Note", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uniqueidentifier");
                    b.Property<Guid?>("CategoryId").HasColumnType("uniqueidentifier");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<Guid?>("CreatedBy").HasColumnType("uniqueidentifier");
                    b.Property<DateTime?>("ExpiresAt").HasColumnType("datetime2");
                    b.Property<bool>("IsPinned").HasColumnType("bit");
                    b.Property<bool>("IsTemplate").HasColumnType("bit");
                    b.Property<byte>("SecurityLevel").HasColumnType("tinyint");
                    b.Property<string>("Title").IsRequired().HasMaxLength(500).HasColumnType("nvarchar(500)");
                    b.Property<DateTime>("UpdatedAt").HasColumnType("datetime2");
                    b.Property<Guid?>("UpdatedBy").HasColumnType("uniqueidentifier");
                    b.Property<Guid>("UserId").HasColumnType("uniqueidentifier");
                    b.HasKey("Id");
                    b.HasIndex("CategoryId");
                    b.HasIndex("ExpiresAt").HasFilter("[ExpiresAt] IS NOT NULL");
                    b.HasIndex("UserId");
                    b.ToTable("notes", (string)null);
                });

            modelBuilder.Entity("ConSecOrg.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uniqueidentifier");
                    b.Property<string>("Name").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                    b.Property<string>("PermissionsJson").IsRequired().HasColumnType("NVARCHAR(MAX)");
                    b.HasKey("Id");
                    b.HasIndex("Name").IsUnique();
                    b.ToTable("roles", (string)null);
                    b.HasData(
                        new { Id = new Guid("11111111-1111-1111-1111-111111111111"), Name = "Admin", PermissionsJson = "{\"notes\":[\"r\",\"c\",\"u\",\"d\"],\"tasks\":[\"r\",\"c\",\"u\",\"d\"],\"contacts\":[\"r\",\"c\",\"u\",\"d\"],\"audit\":[\"r\"],\"users\":[\"r\",\"c\",\"u\",\"d\"]}" },
                        new { Id = new Guid("22222222-2222-2222-2222-222222222222"), Name = "Manager", PermissionsJson = "{\"notes\":[\"r\",\"c\",\"u\",\"d\"],\"tasks\":[\"r\",\"c\",\"u\",\"d\"],\"contacts\":[\"r\",\"c\",\"u\"],\"audit\":[],\"users\":[\"r\"]}" },
                        new { Id = new Guid("33333333-3333-3333-3333-333333333333"), Name = "Auditor", PermissionsJson = "{\"notes\":[\"r\"],\"tasks\":[\"r\"],\"contacts\":[],\"audit\":[\"r\"],\"users\":[\"r\"]}" },
                        new { Id = new Guid("44444444-4444-4444-4444-444444444444"), Name = "User", PermissionsJson = "{\"notes\":[\"r\",\"c\",\"u\",\"d\"],\"tasks\":[\"r\",\"c\",\"u\",\"d\"],\"contacts\":[\"r\",\"c\",\"u\",\"d\"],\"audit\":[],\"users\":[]}" });
                });

            modelBuilder.Entity("ConSecOrg.Domain.Entities.Session", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<string>("DeviceId").HasColumnType("nvarchar(max)");
                    b.Property<DateTime>("ExpiresAt").HasColumnType("datetime2");
                    b.Property<string>("IpAddress").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<byte[]>("KeyMaterial").HasColumnType("varbinary(max)");
                    b.Property<byte[]>("TokenHash").IsRequired().HasColumnType("varbinary(max)");
                    b.Property<string>("UserAgent").HasColumnType("nvarchar(max)");
                    b.Property<Guid>("UserId").HasColumnType("uniqueidentifier");
                    b.HasKey("Id");
                    b.HasIndex("UserId");
                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("ConSecOrg.Domain.Entities.SharedProject", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<Guid?>("CreatedBy").HasColumnType("uniqueidentifier");
                    b.Property<string>("InviteCode").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
                    b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                    b.Property<Guid>("OwnerUserId").HasColumnType("uniqueidentifier");
                    b.Property<DateTime>("UpdatedAt").HasColumnType("datetime2");
                    b.Property<Guid?>("UpdatedBy").HasColumnType("uniqueidentifier");
                    b.HasKey("Id");
                    b.HasIndex("OwnerUserId");
                    b.ToTable("shared_projects", (string)null);
                });

            modelBuilder.Entity("ConSecOrg.Domain.Entities.SharedProjectColumn", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                    b.Property<string>("Color").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
                    b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                    b.Property<int>("Order").HasColumnType("int");
                    b.Property<Guid>("ProjectId").HasColumnType("uniqueidentifier");
                    b.HasKey("Id");
                    b.HasIndex("ProjectId", "Order");
                    b.ToTable("shared_project_columns", (string)null);
                });

            modelBuilder.Entity("ConSecOrg.Domain.Entities.SharedProjectMember", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                    b.Property<bool>("CanEdit").HasColumnType("bit");
                    b.Property<DateTime>("JoinedAt").HasColumnType("datetime2");
                    b.Property<Guid>("ProjectId").HasColumnType("uniqueidentifier");
                    b.Property<Guid>("UserId").HasColumnType("uniqueidentifier");
                    b.HasKey("Id");
                    b.HasIndex("UserId");
                    b.HasIndex("ProjectId", "UserId").IsUnique();
                    b.ToTable("shared_project_members", (string)null);
                });

            modelBuilder.Entity("ConSecOrg.Domain.Entities.SharedProjectTask", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                    b.Property<Guid?>("AssignedUserId").HasColumnType("uniqueidentifier");
                    b.Property<Guid?>("ColumnId").HasColumnType("uniqueidentifier");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<Guid?>("CreatedBy").HasColumnType("uniqueidentifier");
                    b.Property<string>("Description").HasMaxLength(4000).HasColumnType("nvarchar(4000)");
                    b.Property<DateTime?>("DueDate").HasColumnType("datetime2");
                    b.Property<bool>("IsCompleted").HasColumnType("bit");
                    b.Property<int>("Position").HasColumnType("int");
                    b.Property<int>("Priority").HasColumnType("int");
                    b.Property<Guid>("ProjectId").HasColumnType("uniqueidentifier");
                    b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
                    b.Property<string>("Tags").IsRequired().ValueGeneratedOnAdd().HasMaxLength(2000).HasColumnType("nvarchar(2000)").HasDefaultValue("[]");
                    b.Property<string>("Title").IsRequired().HasMaxLength(500).HasColumnType("nvarchar(500)");
                    b.Property<DateTime>("UpdatedAt").HasColumnType("datetime2");
                    b.Property<Guid?>("UpdatedBy").HasColumnType("uniqueidentifier");
                    b.HasKey("Id");
                    b.HasIndex("AssignedUserId");
                    b.HasIndex("ColumnId");
                    b.HasIndex("ProjectId");
                    b.ToTable("shared_project_tasks", (string)null);
                });

            modelBuilder.Entity("ConSecOrg.Domain.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                    b.Property<string>("Name").IsRequired().HasColumnType("nvarchar(max)");
                    b.HasKey("Id");
                    b.ToTable("Tags");
                });

            modelBuilder.Entity("ConSecOrg.Domain.Entities.TaskItem", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uniqueidentifier");
                    b.Property<int>("BoardColumn").HasColumnType("int");
                    b.Property<int>("ColumnPosition").HasColumnType("int");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<Guid?>("CreatedBy").HasColumnType("uniqueidentifier");
                    b.Property<DateTime?>("DueDate").HasColumnType("datetime2");
                    b.Property<byte>("Priority").HasColumnType("tinyint");
                    b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
                    b.Property<string>("Title").IsRequired().HasMaxLength(500).HasColumnType("nvarchar(500)");
                    b.Property<DateTime>("UpdatedAt").HasColumnType("datetime2");
                    b.Property<Guid?>("UpdatedBy").HasColumnType("uniqueidentifier");
                    b.Property<Guid>("UserId").HasColumnType("uniqueidentifier");
                    b.HasKey("Id");
                    b.HasIndex("UserId");
                    b.ToTable("task_items", (string)null);
                });

            modelBuilder.Entity("ConSecOrg.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uniqueidentifier");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<Guid?>("CreatedBy").HasColumnType("uniqueidentifier");
                    b.Property<string>("DeviceId").HasMaxLength(88).HasColumnType("nvarchar(88)");
                    b.Property<string>("Email").IsRequired().HasMaxLength(255).HasColumnType("nvarchar(255)");
                    b.Property<int>("FailedAttempts").HasColumnType("int");
                    b.Property<bool>("IsLocked").HasColumnType("bit");
                    b.Property<DateTime?>("LastLoginAt").HasColumnType("datetime2");
                    b.Property<string>("LastLoginIp").HasMaxLength(45).HasColumnType("nvarchar(45)");
                    b.Property<byte[]>("PasswordHash").IsRequired().HasColumnType("VARBINARY(32)");
                    b.Property<Guid>("RoleId").HasColumnType("uniqueidentifier");
                    b.Property<byte[]>("Salt").IsRequired().HasColumnType("VARBINARY(32)");
                    b.Property<DateTime>("UpdatedAt").HasColumnType("datetime2");
                    b.Property<Guid?>("UpdatedBy").HasColumnType("uniqueidentifier");
                    b.Property<string>("Username").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                    b.HasKey("Id");
                    b.HasIndex("Email").IsUnique();
                    b.HasIndex("RoleId");
                    b.HasIndex("Username").IsUnique();
                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ConSecOrg.Domain.Entities.UserSettings", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                    b.Property<string>("AccentColor").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<int>("FontSize").HasColumnType("int");
                    b.Property<string>("LayoutSettingsJson").HasColumnType("nvarchar(max)");
                    b.Property<string>("Theme").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<Guid>("UserId").HasColumnType("uniqueidentifier");
                    b.HasKey("Id");
                    b.HasIndex("UserId").IsUnique();
                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("note_tags", b =>
                {
                    b.Property<Guid>("NotesId").HasColumnType("uniqueidentifier");
                    b.Property<Guid>("TagsId").HasColumnType("uniqueidentifier");
                    b.HasKey("NotesId", "TagsId");
                    b.HasIndex("TagsId");
                    b.ToTable("note_tags");
                });

            modelBuilder.Entity("ConSecOrg.Domain.Entities.ChatLastRead", b =>
                {
                    b.HasOne("ConSecOrg.Domain.Entities.User", "User").WithMany()
                        .HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("User");
                });

            modelBuilder.Entity("ConSecOrg.Domain.Entities.ChatMessage", b =>
                {
                    b.HasOne("ConSecOrg.Domain.Entities.GroupChat", "GroupChat").WithMany("Messages")
                        .HasForeignKey("GroupChatId").OnDelete(DeleteBehavior.Cascade);
                    b.HasOne("ConSecOrg.Domain.Entities.User", "Sender").WithMany()
                        .HasForeignKey("SenderUserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("GroupChat");
                    b.Navigation("Sender");
                });

            modelBuilder.Entity("ConSecOrg.Domain.Entities.Contact", b =>
                {
                    b.HasOne("ConSecOrg.Domain.Entities.User", "User").WithMany()
                        .HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();

                    b.OwnsOne("ConSecOrg.Domain.ValueObjects.EncryptedContent", "Email", b1 =>
                        {
                            b1.Property<Guid>("ContactId").HasColumnType("uniqueidentifier");
                            b1.Property<string>("AlgorithmId").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)").HasColumnName("email_algorithm");
                            b1.Property<byte[]>("CipherText").IsRequired().HasColumnType("VARBINARY(512)").HasColumnName("email_encrypted");
                            b1.Property<byte[]>("Hmac").IsRequired().HasColumnType("VARBINARY(32)").HasColumnName("email_hmac");
                            b1.Property<byte[]>("Nonce").IsRequired().HasColumnType("VARBINARY(16)").HasColumnName("email_nonce");
                            b1.HasKey("ContactId");
                            b1.ToTable("contacts");
                            b1.WithOwner().HasForeignKey("ContactId");
                        });

                    b.OwnsOne("ConSecOrg.Domain.ValueObjects.EncryptedContent", "Name", b1 =>
                        {
                            b1.Property<Guid>("ContactId").HasColumnType("uniqueidentifier");
                            b1.Property<string>("AlgorithmId").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)").HasColumnName("name_algorithm");
                            b1.Property<byte[]>("CipherText").IsRequired().HasColumnType("VARBINARY(256)").HasColumnName("name_encrypted");
                            b1.Property<byte[]>("Hmac").IsRequired().HasColumnType("VARBINARY(32)").HasColumnName("name_hmac");
                            b1.Property<byte[]>("Nonce").IsRequired().HasColumnType("VARBINARY(16)").HasColumnName("name_nonce");
                            b1.HasKey("ContactId");
                            b1.ToTable("contacts");
                            b1.WithOwner().HasForeignKey("ContactId");
                        });

                    b.OwnsOne("ConSecOrg.Domain.ValueObjects.EncryptedContent", "Notes", b1 =>
                        {
                            b1.Property<Guid>("ContactId").HasColumnType("uniqueidentifier");
                            b1.Property<string>("AlgorithmId").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)").HasColumnName("notes_algorithm");
                            b1.Property<byte[]>("CipherText").IsRequired().HasColumnType("VARBINARY(MAX)").HasColumnName("notes_encrypted");
                            b1.Property<byte[]>("Hmac").IsRequired().HasColumnType("VARBINARY(32)").HasColumnName("notes_hmac");
                            b1.Property<byte[]>("Nonce").IsRequired().HasColumnType("VARBINARY(16)").HasColumnName("notes_nonce");
                            b1.HasKey("ContactId");
                            b1.ToTable("contacts");
                            b1.WithOwner().HasForeignKey("ContactId");
                        });

                    b.OwnsOne("ConSecOrg.Domain.ValueObjects.EncryptedContent", "Phone", b1 =>
                        {
                            b1.Property<Guid>("ContactId").HasColumnType("uniqueidentifier");
                            b1.Property<string>("AlgorithmId").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)").HasColumnName("phone_algorithm");
                            b1.Property<byte[]>("CipherText").IsRequired().HasColumnType("VARBINARY(128)").HasColumnName("phone_encrypted");
                            b1.Property<byte[]>("Hmac").IsRequired().HasColumnType("VARBINARY(32)").HasColumnName("phone_hmac");
                            b1.Property<byte[]>("Nonce").IsRequired().HasColumnType("VARBINARY(16)").HasColumnName("phone_nonce");
                            b1.HasKey("ContactId");
                            b1.ToTable("contacts");
                            b1.WithOwner().HasForeignKey("ContactId");
                        });

                    b.Navigation("Email");
                    b.Navigation("Name").IsRequired();
                    b.Navigation("Notes");
                    b.Navigation("Phone");
                    b.Navigation("User");
                });

            modelBuilder.Entity("ConSecOrg.Domain.Entities.ContactRequest", b =>
                {
                    b.HasOne("ConSecOrg.Domain.Entities.User", "Receiver").WithMany()
                        .HasForeignKey("ReceiverId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.HasOne("ConSecOrg.Domain.Entities.User", "Sender").WithMany()
                        .HasForeignKey("SenderId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.Navigation("Receiver");
                    b.Navigation("Sender");
                });

            modelBuilder.Entity("ConSecOrg.Domain.Entities.GroupChatMember", b =>
                {
                    b.HasOne("ConSecOrg.Domain.Entities.GroupChat", "GroupChat").WithMany("Members")
                        .HasForeignKey("GroupChatId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.HasOne("ConSecOrg.Domain.Entities.User", "User").WithMany()
                        .HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("GroupChat");
                    b.Navigation("User");
                });

            modelBuilder.Entity("ConSecOrg.Domain.Entities.Note", b =>
                {
                    b.HasOne("ConSecOrg.Domain.Entities.Category", "Category").WithMany("Notes")
                        .HasForeignKey("CategoryId").OnDelete(DeleteBehavior.SetNull);
                    b.HasOne("ConSecOrg.Domain.Entities.User", "User").WithMany("Notes")
                        .HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();

                    b.OwnsOne("ConSecOrg.Domain.ValueObjects.EncryptedContent", "Content", b1 =>
                        {
                            b1.Property<Guid>("NoteId").HasColumnType("uniqueidentifier");
                            b1.Property<string>("AlgorithmId").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)").HasColumnName("content_algorithm");
                            b1.Property<byte[]>("CipherText").IsRequired().HasColumnType("VARBINARY(MAX)").HasColumnName("content_encrypted");
                            b1.Property<byte[]>("Hmac").IsRequired().HasColumnType("VARBINARY(32)").HasColumnName("content_hmac");
                            b1.Property<byte[]>("Nonce").IsRequired().HasColumnType("VARBINARY(16)").HasColumnName("content_nonce");
                            b1.HasKey("NoteId");
                            b1.ToTable("notes");
                            b1.WithOwner().HasForeignKey("NoteId");
                        });

                    b.Navigation("Category");
                    b.Navigation("Content").IsRequired();
                    b.Navigation("User");
                });

            modelBuilder.Entity("ConSecOrg.Domain.Entities.Session", b =>
                {
                    b.HasOne("ConSecOrg.Domain.Entities.User", "User").WithMany("Sessions")
                        .HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("User");
                });

            modelBuilder.Entity("ConSecOrg.Domain.Entities.SharedProject", b =>
                {
                    b.HasOne("ConSecOrg.Domain.Entities.User", "Owner").WithMany()
                        .HasForeignKey("OwnerUserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("Owner");
                });

            modelBuilder.Entity("ConSecOrg.Domain.Entities.SharedProjectColumn", b =>
                {
                    b.HasOne("ConSecOrg.Domain.Entities.SharedProject", "Project").WithMany()
                        .HasForeignKey("ProjectId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("Project");
                });

            modelBuilder.Entity("ConSecOrg.Domain.Entities.SharedProjectMember", b =>
                {
                    b.HasOne("ConSecOrg.Domain.Entities.SharedProject", "Project").WithMany("Members")
                        .HasForeignKey("ProjectId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.HasOne("ConSecOrg.Domain.Entities.User", "User").WithMany()
                        .HasForeignKey("UserId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.Navigation("Project");
                    b.Navigation("User");
                });

            modelBuilder.Entity("ConSecOrg.Domain.Entities.SharedProjectTask", b =>
                {
                    b.HasOne("ConSecOrg.Domain.Entities.User", "AssignedUser").WithMany()
                        .HasForeignKey("AssignedUserId").OnDelete(DeleteBehavior.NoAction);
                    b.HasOne("ConSecOrg.Domain.Entities.SharedProject", "Project").WithMany()
                        .HasForeignKey("ProjectId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("AssignedUser");
                    b.Navigation("Project");
                });

            modelBuilder.Entity("ConSecOrg.Domain.Entities.TaskItem", b =>
                {
                    b.HasOne("ConSecOrg.Domain.Entities.User", "User").WithMany()
                        .HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();

                    b.OwnsOne("ConSecOrg.Domain.ValueObjects.EncryptedContent", "Description", b1 =>
                        {
                            b1.Property<Guid>("TaskItemId").HasColumnType("uniqueidentifier");
                            b1.Property<string>("AlgorithmId").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)").HasColumnName("description_algorithm");
                            b1.Property<byte[]>("CipherText").IsRequired().HasColumnType("VARBINARY(MAX)").HasColumnName("description_encrypted");
                            b1.Property<byte[]>("Hmac").IsRequired().HasColumnType("VARBINARY(32)").HasColumnName("description_hmac");
                            b1.Property<byte[]>("Nonce").IsRequired().HasColumnType("VARBINARY(16)").HasColumnName("description_nonce");
                            b1.HasKey("TaskItemId");
                            b1.ToTable("task_items");
                            b1.WithOwner().HasForeignKey("TaskItemId");
                        });

                    b.Navigation("Description");
                    b.Navigation("User");
                });

            modelBuilder.Entity("ConSecOrg.Domain.Entities.User", b =>
                {
                    b.HasOne("ConSecOrg.Domain.Entities.Role", "Role").WithMany("Users")
                        .HasForeignKey("RoleId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.Navigation("Role");
                });

            modelBuilder.Entity("ConSecOrg.Domain.Entities.UserSettings", b =>
                {
                    b.HasOne("ConSecOrg.Domain.Entities.User", "User").WithOne("Settings")
                        .HasForeignKey("ConSecOrg.Domain.Entities.UserSettings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("User");
                });

            modelBuilder.Entity("note_tags", b =>
                {
                    b.HasOne("ConSecOrg.Domain.Entities.Note", null).WithMany()
                        .HasForeignKey("NotesId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.HasOne("ConSecOrg.Domain.Entities.Tag", null).WithMany()
                        .HasForeignKey("TagsId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                });

            modelBuilder.Entity("ConSecOrg.Domain.Entities.Category", b => { b.Navigation("Notes"); });
            modelBuilder.Entity("ConSecOrg.Domain.Entities.GroupChat", b => { b.Navigation("Members"); b.Navigation("Messages"); });
            modelBuilder.Entity("ConSecOrg.Domain.Entities.Role", b => { b.Navigation("Users"); });
            modelBuilder.Entity("ConSecOrg.Domain.Entities.SharedProject", b => { b.Navigation("Members"); });
            modelBuilder.Entity("ConSecOrg.Domain.Entities.User", b =>
                {
                    b.Navigation("Notes");
                    b.Navigation("Sessions");
                    b.Navigation("Settings");
                });
#pragma warning restore 612, 618
        }
    }
}
